version: '3.8'

services:
  traefik:
    image: traefik:${VERSION:-v2.2.1}
    command:
      # - --log.level=DEBUG
      - --providers.docker
      - --providers.docker.network=traefik-net
      - --providers.docker.exposedByDefault=false
      - --providers.docker.swarmMode=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --entrypoints.http.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - { target: 80, published: 80, mode: host, protocol: tcp }

networks:
  default:
    external: true
    name: traefik-net
